### ISSUE TITLE
Flatpak segfaults

### ISSUE THREAD

**Issue by tpikonen** [rinigus/osmscout-server#422]
OSMScout server GUI installed from flatpak segfaults for me (on Debian bookworm):

```
$ flatpak run --command=sh io.github.rinigus.OSMScoutServer
[📦 io.github.rinigus.OSMScoutServer ~]$ /app/bin/osmscout-server-gui 
QSocketNotifier: Can only be used with threads started with QThread
kf.kirigami: Failed to find a Kirigami platform plugin
Segmentation fault (core dumped)
```

Installing the SDK and running with `--devel` gives access to `gdb` which produces this backtrace:

```
Starting program: /app/bin/osmscout-server-gui 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff1fff640 (LWP 63)]
QSocketNotifier: Can only be used with threads started with QThread
[New Thread 0x7fffebfff640 (LWP 64)]
[New Thread 0x7fffeb7fe640 (LWP 65)]
[New Thread 0x7fffeaffd640 (LWP 66)]
[New Thread 0x7fffea7fc640 (LWP 67)]
[New Thread 0x7fffe9ffb640 (LWP 68)]
[New Thread 0x7fffe97fa640 (LWP 69)]
[New Thread 0x7fffd25ff640 (LWP 70)]
[New Thread 0x7fffd1dfe640 (LWP 71)]
[New Thread 0x7fffd15fd640 (LWP 72)]
[New Thread 0x7fffd0dfc640 (LWP 73)]
kf.kirigami: Failed to find a Kirigami platform plugin

Thread 8 "QQmlThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe97fa640 (LWP 69)]
0x00007ffff651ae30 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
(gdb) bt
#0  0x00007ffff651ae30 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#1  0x00007ffff651b80d in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#2  0x00007ffff651607d in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#3  0x00007ffff6466ae5 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#4  0x00007ffff646c743 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#5  0x00007ffff645a6a5 in QQmlDataBlob::tryDone() () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#6  0x00007ffff64b9f8c in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#7  0x00007ffff64ba692 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#8  0x00007ffff64bba0f in QQmlTypeLoader::loadThread(QQmlDataBlob*) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#9  0x00007ffff64bbe7c in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#10 0x00007ffff64bc720 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#11 0x00007ffff646b80c in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#12 0x00007ffff646e420 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#13 0x00007ffff64ba229 in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#14 0x00007ffff64ba692 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#15 0x00007ffff64bba0f in QQmlTypeLoader::loadThread(QQmlDataBlob*) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#16 0x00007ffff64760bd in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#17 0x00007ffff653589c in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#18 0x00007ffff6536002 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#19 0x00007ffff717b01e in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff5ccdfa8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff5cd0f41 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff5d26c23 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff5120d71 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff5177028 in g_main_context_iterate.constprop () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff511e4a3 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff5d26306 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007ffff5ccca1b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007ffff5ad8567 in QThread::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007ffff6535555 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#30 0x00007ffff5ad976d in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007ffff528f1da in start_thread () at /usr/lib/x86_64-linux-gnu/libc.so.6
#32 0x00007ffff5317f44 in clone () at /usr/lib/x86_64-linux-gnu/libc.so.6
```

On the other hand, my Debian installation apparently has all the necessary libraries, since running the flatpak binary without containerization directly from the shell works:

```
$ ~/.local/share/flatpak/app/io.github.rinigus.OSMScoutServer/current/active/files/bin/osmscout-server-gui 
QSocketNotifier: Can only be used with threads started with QThread
kf.kirigami: Failed to find a Kirigami platform plugin
file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/private/PrivateActionToolButton.qml:70:5: QML Binding: Binding loop detected for property "value"
```

I remember that flatpak of version 3.0.0 used to work fine, but apparently some upgrade in Debian or flatpak broke it. Re-installing the org.kde.Platform and the OSMScout flatpak did not help.

**Comment by rinigus** [comment]
Try to wipe OSM Scout Server cache that is under ~/.var/app/io.github.rinigus.OSMScoutServer . Sometimes qml caches get messed up.

**Comment by tpikonen** [comment]
Thanks, deleting the cache fixed this.

**Comment by rinigus** [comment]
Excellent!
